//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.6
//
// <auto-generated>
//
// Generated from file `VS.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#include <VS.h>
#include <IceUtil/PushDisableWarnings.h>
#include <Ice/LocalException.h>
#include <Ice/ValueFactory.h>
#include <Ice/OutgoingAsync.h>
#include <Ice/InputStream.h>
#include <Ice/OutputStream.h>
#include <IceUtil/PopDisableWarnings.h>

#if defined(_MSC_VER)
#   pragma warning(disable:4458) // declaration of ... hides class member
#elif defined(__clang__)
#   pragma clang diagnostic ignored "-Wshadow"
#elif defined(__GNUC__)
#   pragma GCC diagnostic ignored "-Wshadow"
#endif

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 307
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 >= 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 6
#       error Ice patch level mismatch!
#   endif
#endif

#ifdef ICE_CPP11_MAPPING // C++11 mapping

namespace
{

const ::std::string iceC_VideoStreaming_VS_ids[2] =
{
    "::Ice::Object",
    "::VideoStreaming::VS"
};
const ::std::string iceC_VideoStreaming_VS_ops[] =
{
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping",
    "initVideoStreamingApp"
};
const ::std::string iceC_VideoStreaming_VS_initVideoStreamingApp_name = "initVideoStreamingApp";

}

bool
VideoStreaming::VS::ice_isA(::std::string s, const ::Ice::Current&) const
{
    return ::std::binary_search(iceC_VideoStreaming_VS_ids, iceC_VideoStreaming_VS_ids + 2, s);
}

::std::vector<::std::string>
VideoStreaming::VS::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector<::std::string>(&iceC_VideoStreaming_VS_ids[0], &iceC_VideoStreaming_VS_ids[2]);
}

::std::string
VideoStreaming::VS::ice_id(const ::Ice::Current&) const
{
    return ice_staticId();
}

const ::std::string&
VideoStreaming::VS::ice_staticId()
{
    static const ::std::string typeId = "::VideoStreaming::VS";
    return typeId;
}

/// \cond INTERNAL
bool
VideoStreaming::VS::_iceD_initVideoStreamingApp(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Idempotent, current.mode);
    inS.readEmptyParams();
    this->initVideoStreamingApp(current);
    inS.writeEmptyParams();
    return true;
}
/// \endcond

/// \cond INTERNAL
bool
VideoStreaming::VS::_iceDispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair<const ::std::string*, const ::std::string*> r = ::std::equal_range(iceC_VideoStreaming_VS_ops, iceC_VideoStreaming_VS_ops + 5, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - iceC_VideoStreaming_VS_ops)
    {
        case 0:
        {
            return _iceD_ice_id(in, current);
        }
        case 1:
        {
            return _iceD_ice_ids(in, current);
        }
        case 2:
        {
            return _iceD_ice_isA(in, current);
        }
        case 3:
        {
            return _iceD_ice_ping(in, current);
        }
        case 4:
        {
            return _iceD_initVideoStreamingApp(in, current);
        }
        default:
        {
            assert(false);
            throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
        }
    }
}
/// \endcond

/// \cond INTERNAL
void
VideoStreaming::VSPrx::_iceI_initVideoStreamingApp(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<void>>& outAsync, const ::Ice::Context& context)
{
    outAsync->invoke(iceC_VideoStreaming_VS_initVideoStreamingApp_name, ::Ice::OperationMode::Idempotent, ::Ice::FormatType::DefaultFormat, context,
        nullptr,
        nullptr);
}
/// \endcond

/// \cond INTERNAL
::std::shared_ptr<::Ice::ObjectPrx>
VideoStreaming::VSPrx::_newInstance() const
{
    return ::IceInternal::createProxy<VSPrx>();
}
/// \endcond

const ::std::string&
VideoStreaming::VSPrx::ice_staticId()
{
    return VS::ice_staticId();
}

#else // C++98 mapping

namespace
{

const ::std::string iceC_VideoStreaming_VS_initVideoStreamingApp_name = "initVideoStreamingApp";

}

/// \cond INTERNAL
::IceProxy::Ice::Object* ::IceProxy::VideoStreaming::upCast(VS* p) { return p; }

void
::IceProxy::VideoStreaming::_readProxy(::Ice::InputStream* istr, ::IceInternal::ProxyHandle< VS>& v)
{
    ::Ice::ObjectPrx proxy;
    istr->read(proxy);
    if(!proxy)
    {
        v = 0;
    }
    else
    {
        v = new VS;
        v->_copyFrom(proxy);
    }
}
/// \endcond

::Ice::AsyncResultPtr
IceProxy::VideoStreaming::VS::_iceI_begin_initVideoStreamingApp(const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_VideoStreaming_VS_initVideoStreamingApp_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_VideoStreaming_VS_initVideoStreamingApp_name, ::Ice::Idempotent, context);
        result->writeEmptyParams();
        result->invoke(iceC_VideoStreaming_VS_initVideoStreamingApp_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

void
IceProxy::VideoStreaming::VS::end_initVideoStreamingApp(const ::Ice::AsyncResultPtr& result)
{
    _end(result, iceC_VideoStreaming_VS_initVideoStreamingApp_name);
}

/// \cond INTERNAL
::IceProxy::Ice::Object*
IceProxy::VideoStreaming::VS::_newInstance() const
{
    return new VS;
}
/// \endcond

const ::std::string&
IceProxy::VideoStreaming::VS::ice_staticId()
{
    return ::VideoStreaming::VS::ice_staticId();
}

VideoStreaming::VS::~VS()
{
}

/// \cond INTERNAL
::Ice::Object* VideoStreaming::upCast(VS* p) { return p; }

/// \endcond

namespace
{
const ::std::string iceC_VideoStreaming_VS_ids[2] =
{
    "::Ice::Object",
    "::VideoStreaming::VS"
};

}

bool
VideoStreaming::VS::ice_isA(const ::std::string& s, const ::Ice::Current&) const
{
    return ::std::binary_search(iceC_VideoStreaming_VS_ids, iceC_VideoStreaming_VS_ids + 2, s);
}

::std::vector< ::std::string>
VideoStreaming::VS::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector< ::std::string>(&iceC_VideoStreaming_VS_ids[0], &iceC_VideoStreaming_VS_ids[2]);
}

const ::std::string&
VideoStreaming::VS::ice_id(const ::Ice::Current&) const
{
    return ice_staticId();
}

const ::std::string&
VideoStreaming::VS::ice_staticId()
{
#ifdef ICE_HAS_THREAD_SAFE_LOCAL_STATIC
    static const ::std::string typeId = "::VideoStreaming::VS";
    return typeId;
#else
    return iceC_VideoStreaming_VS_ids[1];
#endif
}

/// \cond INTERNAL
bool
VideoStreaming::VS::_iceD_initVideoStreamingApp(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Idempotent, current.mode);
    inS.readEmptyParams();
    this->initVideoStreamingApp(current);
    inS.writeEmptyParams();
    return true;
}
/// \endcond

namespace
{
const ::std::string iceC_VideoStreaming_VS_all[] =
{
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping",
    "initVideoStreamingApp"
};

}

/// \cond INTERNAL
bool
VideoStreaming::VS::_iceDispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair<const ::std::string*, const ::std::string*> r = ::std::equal_range(iceC_VideoStreaming_VS_all, iceC_VideoStreaming_VS_all + 5, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - iceC_VideoStreaming_VS_all)
    {
        case 0:
        {
            return _iceD_ice_id(in, current);
        }
        case 1:
        {
            return _iceD_ice_ids(in, current);
        }
        case 2:
        {
            return _iceD_ice_isA(in, current);
        }
        case 3:
        {
            return _iceD_ice_ping(in, current);
        }
        case 4:
        {
            return _iceD_initVideoStreamingApp(in, current);
        }
        default:
        {
            assert(false);
            throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
        }
    }
}
/// \endcond

/// \cond STREAM
void
VideoStreaming::VS::_iceWriteImpl(::Ice::OutputStream* ostr) const
{
    ostr->startSlice(ice_staticId(), -1, true);
    ::Ice::StreamWriter< VS, ::Ice::OutputStream>::write(ostr, *this);
    ostr->endSlice();
}

void
VideoStreaming::VS::_iceReadImpl(::Ice::InputStream* istr)
{
    istr->startSlice();
    ::Ice::StreamReader< VS, ::Ice::InputStream>::read(istr, *this);
    istr->endSlice();
}
/// \endcond

/// \cond INTERNAL
void
VideoStreaming::_icePatchObjectPtr(VSPtr& handle, const ::Ice::ObjectPtr& v)
{
    handle = VSPtr::dynamicCast(v);
    if(v && !handle)
    {
        IceInternal::Ex::throwUOE(VS::ice_staticId(), v);
    }
}
/// \endcond

namespace Ice
{
}

#endif
